[2023-07-13 22:18:46,835] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_stock_data_google_DAG.execute_python_script manual__2023-07-13T22:18:45.835744+00:00 [queued]>
[2023-07-13 22:18:46,844] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_stock_data_google_DAG.execute_python_script manual__2023-07-13T22:18:45.835744+00:00 [queued]>
[2023-07-13 22:18:46,845] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 22:18:46,845] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2023-07-13 22:18:46,846] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 22:18:46,860] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): execute_python_script> on 2023-07-13 22:18:45.835744+00:00
[2023-07-13 22:18:46,863] {standard_task_runner.py:52} INFO - Started process 238 to run task
[2023-07-13 22:18:46,866] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_stock_data_google_DAG', 'execute_python_script', 'manual__2023-07-13T22:18:45.835744+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/ETL_stock_data_google_DAG.py', '--cfg-path', '/tmp/tmpt7oiaogf', '--error-file', '/tmp/tmpl67n1anb']
[2023-07-13 22:18:46,867] {standard_task_runner.py:80} INFO - Job 27: Subtask execute_python_script
[2023-07-13 22:18:46,915] {logging_mixin.py:109} INFO - Running <TaskInstance: ETL_stock_data_google_DAG.execute_python_script manual__2023-07-13T22:18:45.835744+00:00 [running]> on host a917c5d777dc
[2023-07-13 22:18:46,963] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fvinciguerra
AIRFLOW_CTX_DAG_ID=ETL_stock_data_google_DAG
AIRFLOW_CTX_TASK_ID=execute_python_script
AIRFLOW_CTX_EXECUTION_DATE=2023-07-13T22:18:45.835744+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-13T22:18:45.835744+00:00
[2023-07-13 22:18:46,964] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-13 22:18:46,966] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python pyscripts.ETL_stock_data_google']
[2023-07-13 22:18:46,971] {subprocess.py:85} INFO - Output:
[2023-07-13 22:18:47,040] {subprocess.py:89} INFO - python: can't open file 'pyscripts.ETL_stock_data_google': [Errno 2] No such file or directory
[2023-07-13 22:18:47,043] {subprocess.py:93} INFO - Command exited with return code 2
[2023-07-13 22:18:47,053] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-13 22:18:47,058] {taskinstance.py:1278} INFO - Marking task as FAILED. dag_id=ETL_stock_data_google_DAG, task_id=execute_python_script, execution_date=20230713T221845, start_date=20230713T221846, end_date=20230713T221847
[2023-07-13 22:18:47,070] {standard_task_runner.py:93} ERROR - Failed to execute job 27 for task execute_python_script (Bash command failed. The command returned a non-zero exit code 2.; 238)
[2023-07-13 22:18:47,079] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-07-13 22:18:47,101] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
